version: '3'
services:
  ledserver-controller-html:
    build: clients/controller-html
    ports:
      - "8080:80"
    image: ${USER}/ledserver-controller-html
  ledserver:
    build: server
    ports:
      - "8001:8001"
      - "8002:8002"
    image: ${USER}/ledserver
    user: "${UID}:${GID}"
    #volumes: 
    #  - ./server:/usr/src/server
    #command: python3.7 /usr/src/server/LEDServer.py
    
  
